import type { Metadata } from "next";
import {Geist, Geist_Mono, Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import React from "react";
import {getCurrentSession} from "@/action/auths";
import {SanityLive} from "@/sanity/lib/live";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inter = Inter({subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const {user} = await getCurrentSession();
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-white min-h-[125vh]`}
      >
      <Header user={user}></Header>
        {children}
      <SanityLive/>
      </body>
    </html>
  );
}
